timezone: "America/Denver"
permalink: "/blog/:year-:month-:day/:title"
paginate_path: "/blog/page-:num/"
paginate: 20
gems:
- jekyll-paginate
defaults:
  values:
    layout: post
url: http://mke8.me
name: "mkeedlinger's home"